#!/usr/bin/env bash

HK_SELF=`basename "$0"`
HK_GIT_DIR="${HOME}/.homekeeper"
HK_WORK_TREE="${HOME}"
HK_CMD="git --git-dir="${HK_GIT_DIR}" --work-tree="${HK_WORK_TREE}""

function hk_help {
	echo "# Homekeeper"
	echo "# https://github.com/zemm/homekeeper"
	echo "#"
	echo "# Git wrapper to maintain your dotfiles"
	echo "#"
	echo "# Using: ${HK_CMD}"
	echo "#"
	echo "# Commands:"
	echo "#   $HK_SELF [help|-h|--help]  # This help"
	echo "#   $HK_SELF ls|versioned      # List managed files"
	echo "#   $HK_SELF arg1 [arg2 [..]]  # Passthrough to git"
}

function hk_help_init {
	echo "### It seems that Homekeeper is not initialized!"
	echo "#"
	echo "#  ## Preparations"
	echo "#  ## ------------"
	echo "#  # Create your remote bare dotfiles repo somewhere (github?)"
	echo "#"
	echo "#  ## To initialize"
	echo "#  ## -------------"
	echo "#  $ ${HK_SELF} init"
	echo "#  $ ${HK_SELF} remote add origin DOTFILES_REPO_URL"
	echo "#"
	echo "#  ## On empty freshly created dotfiles repo"
	echo "#  ## --------------------------------------"
	echo "#  $ echo '*' >> ~/.gitignore"
	echo "#  $ ${HK_SELF} add --force ~/.gitignore"
	echo "#  $ ${HK_SELF} commit -m \"Ignore everything by default; be explicit\""
	echo "#  $ ${HK_SELF} push origin master"
	echo "#"
	echo "#  ## On existing dotfiles repo"
	echo "#  ## -------------------------"
	echo "#  ## WARNING: Destuctive operation! Will overwrite local files that"
	echo "#  ## exist in the dotfiles repo!"
	echo "#  $ ${HK_SELF} pull origin master"
	echo "#  $ ${HK_SELF} checkout -f master"
	echo "#"
	echo "#  ## Start using with regular git commands, just"
	echo "#  ## '${HK_SELF}' instead of 'git'."
	echo "#  ## Add new files with --force"
}

function hk_is_initialized {
	test -d "${HK_GIT_DIR}"
}

case $1 in
	'' | 'help' | '-h' | '--help' )
		hk_help
		hk_is_initialized || (echo; hk_help_init; exit 1)
		;;

	'ls' | 'versioned' )
		echo "# Managed dotfiles"
		$HK_CMD  ls-tree -r --name-only HEAD "${HK_WORK_TREE}"
		;;

	*)
		if ! hk_is_initialized && [[ "$1" != "init" ]]; then
			hk_help_init
			exit 1
		else
			$HK_CMD "$@"
		fi
		;;
esac
